### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by lurkshark** [standardnotes/editor-kit#16]
I found this library after looking at the implementation of your [token-vault editor](https://github.com/standardnotes/token-vault) and noticed that it appears to only be licensed AGPL. My understanding of the license is that this would force the token-vault editor project to assume the AGPL license as well.

Since both of these are Standard Notes projects it's not a huge deal, but I was curious if you guys are dual-licensing this library or switching to a MIT-style license.

Appreciate the work y'all are doing!

**Edit:** Also in the case of a dual-license situation I'm curious if you plan on accepting contributions from outsiders to this library, as you would likely need a contributor license agreement or something similar in place.

**Edit:** Just noticed this is built on the [component-relay](https://github.com/standardnotes/component-relay) which is also AGPL, so I guess the question balloons into an issue of AGPL turtles all the way down.

**Comment by JaspalSuri** [comment]
Hi @lurkshark, thanks for asking. I'll forward your questions to members of the dev team.

**Comment by atmoio** [comment]
Hey @lurkshark, good question. I might suppose that Standard Notes will have issued TokenVault a "do whatever you want with this library" type licensing arrangement and not the standard AGPL license. So indeed dual-license, but this is all implicit since we are the creator of both projects. Software licensing, especially with AGPL, can be endlessly confusing so we'll do our best to clean up any missing gaps as we encounter them. I suppose as an initial step with the new TokenVault update, we simply wanted to announce our intention to shift TokenVault from open-source to public-source.

**Comment by lurkshark** [comment]
Thanks for the answer! That's more-or-less what I assumed. You might want to consider a CLA for SN projects in case anyone external has a useful contribution.
